### ISSUE TITLE
Tests in error when run mvn clean package.

### ISSUE THREAD

**Issue by skanel** [simplesteph/medium-blog-kafka-udemy#1]
Results :

Tests in error: 
  UdemyRESTClientTest.twoApiCallsReturnTwoDifferentSetsOfResults:114 » JSON JSON...
  UdemyRESTClientTest.apiCallIsSuccessful:35 » JSON JSONObject["id"] not found.

Tests run: 5, Failures: 0, Errors: 2, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] udemy-reviews-producer ............................. FAILURE [ 14.525 s]
[INFO] udemy-reviews-fraud ................................ SKIPPED
[INFO] udemy-reviews-aggregator ........................... SKIPPED
[INFO] udemy-reviews-parent-project ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.999 s
[INFO] Finished at: 2018-07-12T07:51:25+07:00
[INFO] Final Memory: 24M/166M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project udemy-reviews-producer: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/knel/Projects/abc/udemy-reviews-producer/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
knel@kso:~/Projects/abc$

**Comment by simplesteph** [comment]
Probably some changes in the Udemy API 
If you want to do a PR I'll review !

**Comment by matiwinnetou** [comment]
Yes, I have the same issue.

**Comment by matiwinnetou** [comment]
@simplesteph @skanel this PR fixes issue with Udemy API, they introduced a backwards incompatible change. https://github.com/simplesteph/medium-blog-kafka-udemy/pull/2

**Comment by matiwinnetou** [comment]
@simplesteph  please have a look again at the fixes in PR, I reverted the changes you requested. I can tell you that I tested all 3 components locally and they basically work.

**Comment by simplesteph** [comment]
thanks @matiwinnetou for the contribution! Looks great :)
